import fbx
import sys
import os
class MapBones:
    def __init__(self):
        self.mapBones = {
            0: "replace",
            1: "replace",
            2: "replace",
            3: "b_pelvis",
            4: "replace",
            5: "b_l_thigh",
            6: "b_r_thigh",
            7: "b_r_glut_ctwist",
            8: "replace",
            9: "replace",
            10: "replace",
            11: "replace",
            12: "replace",
            13: "replace",
            14: "b_spine1",
            15: "b_l_glut_ctwist",
            16: "replace",
            17: "replace",
            18: "replace",
            19: "b_spine3",
            20: "replace",
            21: "b_spine2",
            22: "replace",
            23: "replace",
            24: "b_neck0_twist",
            25: "replace",
            26: "replace",
            27: "replace",
            28: "replace",
            29: "replace",
            30: "replace",
            31: "replace",
            32: "replace",
            33: "replace",
            34: "replace",
            35: "replace",
            36: "replace",
            37: "replace",
            38: "replace",
            39: "replace",
            40: "replace",
            41: "replace",
            42: "replace",
            43: "replace",
            44: "replace",
            45: "replace",
            46: "replace",
            47: "replace",
            48: "b_r_clav",
            49: "replace",
            50: "replace",
            51: "b_head",
            52: "b_l_clav",
            53: "replace",
            54: "b_neck1_twist",
            55: "replace",
            56: "replace",
            57: "replace",
            58: "replace",
            59: "replace",
            60: "replace",
            61: "replace",
            62: "replace",
            63: "replace",
            64: "replace",
            65: "replace",
            66: "replace",
            67: "replace",
            68: "replace",
            69: "replace",
            70: "replace",
            71: "replace",
            72: "replace",
            73: "replace",
            74: "replace",
            75: "replace",
            76: "replace",
            77: "replace",
            78: "replace",
            79: "replace",
            80: "replace",
            81: "replace",
            82: "replace",
            83: "replace",
            84: "replace",
            85: "replace",
            86: "replace",
            87: "replace",
            88: "replace",
            89: "replace",
            90: "replace",
            91: "replace",
            92: "replace",
            93: "replace",
            94: "replace",
            95: "replace",
            96: "replace",
            97: "replace",
            98: "replace",
            99: "replace",
            100: "replace",
            101: "replace",
            102: "replace",
            103: "replace",
            104: "replace",
            105: "replace",
            106: "replace",
            107: "replace",
            108: "replace",
            109: "replace",
            110: "replace",
            111: "replace",
            112: "replace",
            113: "replace",
            114: "replace",
            115: "replace",
            116: "replace",
            117: "replace",
            118: "replace",
            119: "replace",
            120: "replace",
            121: "replace",
            122: "replace"
        }
        self.bonesNames = [
            "RootNode",
            "masterchief_world",
            "b_pedestal",
            "b_aim_pitch",
            "b_aim_yaw",
            "b_pelvis",
            "b_cog_null",
            "b_spine1",
            "b_spine2",
            "b_spine3",
            "b_neck0",
            "b_neck1",
            "b_head",
            "b_head_null",
            "backarmor_dist1",
            "neck_twist_HDL",
            "head_eff_cls_hmnul",
            "head_eff_CLS",
            "b_helmet",
            "neck_ctwist_HDL",
            "head_cls_hmnul",
            "head_CLS",
            "neck1_cls_hmnul",
            "neck1_CLS",
            "b_neck1_twist",
            "spine_ik_twist_HDL",
            "spine3_eff_cls_hmnul",
            "spine3_eff_CLS",
            "neck0_cls_hmnul",
            "neck0_CLS",
            "b_neck0_twist",
            "b_l_clav",
            "b_l_upperarm",
            "b_l_forearm",
            "b_l_hand",
            "b_l_hand_null",
            "b_l_thumb1",
            "b_l_thumb2",
            "b_l_thumb3",
            "b_l_thumb_null",
            "b_l_index1",
            "b_l_index2",
            "b_l_index3",
            "b_l_index_null",
            "b_l_middle1",
            "b_l_middle2",
            "b_l_middle3",
            "b_l_middle_null",
            "b_l_ring1",
            "b_l_ring2",
            "b_l_ring3",
            "b_l_ring_null",
            "b_l_pinky0",
            "b_l_pinky1",
            "b_l_pinky2",
            "b_l_pinky3",
            "b_l_pinky_null",
            "b_l_wrist_fixup",
            "b_l_grip",
            "b_l_hand_helper3",
            "b_l_hand_helper4",
            "b_l_hand_helper1",
            "b_l_hand_helper2",
            "l_hand_ctwist_HDL",
            "b_l_forearm_fixup",
            "b_l_hand_twist",
            "l_upperarm_ctwist_HDL",
            "b_l_forearm_helper4",
            "b_l_forearm_helper3",
            "b_l_forearm_helper2",
            "b_l_forearm_helper1",
            "b_l_hand_ctwist",
            "l_hand_ctwist",
            "b_l_hand_ctwist_null",
            "b_l_elbow_fixup",
            "b_l_elbow_fixup_null",
            "b_l_elbow_armor",
            "b_l_elbow_armor_null",
            "l_upperarm_fixup_distloc2",
            "b_l_upperarm_fixup",
            "b_l_upperarm_fixup_null",
            "b_l_shoulder_fixup",
            "l_upperarm_ctwist",
            "b_l_shoulder_helper1",
            "b_l_shoulder_helper2",
            "b_l_shoulder_helper3",
            "b_l_shoulder_helper4",
            "b_l_upperarm_ctwist",
            "b_l_upperarm_ctwist_null",
            "b_r_scap_aim_null",
            "b_r_clav",
            "b_r_upperarm",
            "b_r_forearm",
            "b_r_hand",
            "b_r_hand_null",
            "b_r_index1",
            "b_r_index2",
            "b_r_index3",
            "b_r_index_null",
            "b_r_middle1",
            "b_r_middle2",
            "b_r_middle3",
            "b_r_middle_null",
            "b_r_pinky0",
            "b_r_pinky1",
            "b_r_pinky2",
            "b_r_pinky3",
            "b_r_pinky_null",
            "b_r_ring1",
            "b_r_ring2",
            "b_r_ring3",
            "b_r_ring_null",
            "b_r_thumb1",
            "b_r_thumb2",
            "b_r_thumb3",
            "b_r_thumb_null",
            "b_r_wrist_fixup",
            "b_r_grip",
            "r_hand_ctwist_HDL",
            "b_r_hand_helper1",
            "b_r_hand_helper2",
            "b_r_hand_helper3",
            "b_r_hand_helper4",
            "b_r_hand_twist",
            "b_r_forearm_fixup",
            "b_r_hand_ctwist",
            "b_r_hand_ctwist_null",
            "r_hand_ctwist",
            "r_upperarm_ctwist_HDL",
            "b_r_forearm_helper4",
            "b_r_forearm_helper3",
            "b_r_forearm_helper2",
            "b_r_forearm_helper1",
            "b_r_elbow_fixup",
            "b_r_elbow_fixup_null",
            "b_r_elbow_armor",
            "b_r_elbow_armor_null",
            "r_upperarm_fixup_distloc2",
            "b_r_shoulder_fixup",
            "b_r_upperarm_fixup",
            "b_r_upperarm_fixup_null",
            "r_upperarm_ctwist",
            "b_r_shoulder_helper1",
            "b_r_shoulder_helper2",
            "b_r_shoulder_helper3",
            "b_r_shoulder_helper4",
            "b_r_upperarm_ctwist",
            "b_r_upperarm_ctwist_null",
            "b_l_scap_aim_null",
            "b_torso",
            "b_backpack",
            "b_l_scap1",
            "b_l_scap2",
            "b_l_scap3",
            "b_l_scap_null",
            "b_r_scap1",
            "b_r_scap2",
            "b_r_scap3",
            "b_r_scap_null",
            "b_l_clav_aim_null",
            "b_l_clav_aim_null1",
            "b_r_scap_upv",
            "b_l_scap_upv",
            "b_l_lowerback_armor",
            "b_l_lowerback_armor_null",
            "b_abarmor",
            "b_abarmor_null",
            "b_backarmor",
            "b_backarmor_null",
            "b_r_lowerback_armor",
            "b_r_lowerback_armor_null",
            "backarmor_dist2",
            "backarmor_distDimen1",
            "b_camera",
            "b_camera_null",
            "b_neck0_ik",
            "b_neck1_ik",
            "b_head_ik",
            "b_head_ik_eff",
            "b_head_ctwist",
            "b_head_ctwist_null",
            "neck_ctwist_null",
            "spine_ctwist_HDL",
            "spine3_cls_hmnul",
            "spine3_CLS",
            "spine2_cls_hmnul",
            "spine2_CLS",
            "b_spine2_twist",
            "spine1_cls_hmnul",
            "spine1_CLS",
            "b_spine1_twist",
            "l_upperarm_fixup_distloc1",
            "l_upperarm_dist",
            "r_upperarm_fixup_distloc1",
            "r_upperarm_fixup_dist",
            "b_l_thigh",
            "b_l_calf",
            "b_l_foot",
            "b_l_heel_null",
            "b_l_toe",
            "b_l_toe_null",
            "b_l_ball_null",
            "b_l_calf_jiggle",
            "l_thigh_ctwist_HDL",
            "b_l_upperleg_jiggle",
            "b_l_knee_fixup",
            "b_l_knee_fixup_null",
            "b_l_thigh_helper",
            "l_thigh_ctwist",
            "b_r_thigh",
            "b_r_calf",
            "b_r_foot",
            "b_r_heel_null",
            "b_r_toe",
            "b_r_toe_null",
            "b_r_ball_null",
            "b_r_calf_jiggle",
            "r_thigh_ctwist_HDL",
            "b_r_upperleg_jiggle",
            "b_r_knee_fixup",
            "b_r_knee_fixup_null",
            "b_r_thigh_helper",
            "r_thigh_ctwist",
            "b_r_thigh_ctwist",
            "b_r_thigh_ctwist_null",
            "b_l_thigh_ctwist",
            "b_l_thigh_ctwist_null",
            "b_l_glut_ctwist",
            "b_r_glut_ctwist",
            "b_spine1_ik",
            "b_spine2_ik",
            "b_spine3_ik",
            "b_spine3_ik_eff",
            "b_spine_ctwist",
            "b_spine_ctwist_null",
            "spine_ctwist_null"
        ]
        self.bonesNamesThreejs = [
            "skel:masterchief_world",
            "skel:b_pedestal",
            "skel:b_aim_pitch",
            "skel:b_aim_yaw",
            "skel:b_pelvis",
            "skel:b_spine1",
            "skel:b_spine2",
            "skel:b_spine3",
            "skel:b_neck0",
            "skel:b_neck1",
            "skel:b_head",
            "skel:b_helmet",
            "skel:b_neck1_twist",
            "skel:b_neck0_twist",
            "skel:b_l_clav",
            "skel:b_l_upperarm",
            "skel:b_l_forearm",
            "skel:b_l_hand",
            "skel:b_l_thumb1",
            "skel:b_l_thumb2",
            "skel:b_l_thumb3",
            "skel:b_l_index1",
            "skel:b_l_index2",
            "skel:b_l_index3",
            "skel:b_l_middle1",
            "skel:b_l_middle2",
            "skel:b_l_middle3",
            "skel:b_l_ring1",
            "skel:b_l_ring2",
            "skel:b_l_ring3",
            "skel:b_l_pinky0",
            "skel:b_l_pinky1",
            "skel:b_l_pinky2",
            "skel:b_l_pinky3",
            "skel:b_l_wrist_fixup",
            "skel:b_l_grip",
            "skel:b_l_hand_helper3",
            "skel:b_l_hand_helper4",
            "skel:b_l_hand_helper1",
            "skel:b_l_hand_helper2",
            "skel:b_l_forearm_fixup",
            "skel:b_l_hand_twist",
            "skel:b_l_forearm_helper4",
            "skel:b_l_forearm_helper3",
            "skel:b_l_forearm_helper2",
            "skel:b_l_forearm_helper1",
            "skel:b_l_hand_ctwist",
            "skel:b_l_elbow_fixup",
            "skel:b_l_elbow_armor",
            "skel:b_l_upperarm_fixup",
            "skel:b_l_shoulder_fixup",
            "skel:b_l_shoulder_helper1",
            "skel:b_l_shoulder_helper2",
            "skel:b_l_shoulder_helper3",
            "skel:b_l_shoulder_helper4",
            "skel:b_l_upperarm_ctwist",
            "skel:b_r_clav",
            "skel:b_r_upperarm",
            "skel:b_r_forearm",
            "skel:b_r_hand",
            "skel:b_r_index1",
            "skel:b_r_index2",
            "skel:b_r_index3",
            "skel:b_r_middle1",
            "skel:b_r_middle2",
            "skel:b_r_middle3",
            "skel:b_r_pinky0",
            "skel:b_r_pinky1",
            "skel:b_r_pinky2",
            "skel:b_r_pinky3",
            "skel:b_r_ring1",
            "skel:b_r_ring2",
            "skel:b_r_ring3",
            "skel:b_r_thumb1",
            "skel:b_r_thumb2",
            "skel:b_r_thumb3",
            "skel:b_r_wrist_fixup",
            "skel:b_r_grip",
            "skel:b_r_hand_helper1",
            "skel:b_r_hand_helper2",
            "skel:b_r_hand_helper3",
            "skel:b_r_hand_helper4",
            "skel:b_r_hand_twist",
            "skel:b_r_forearm_fixup",
            "skel:b_r_hand_ctwist",
            "skel:b_r_forearm_helper4",
            "skel:b_r_forearm_helper3",
            "skel:b_r_forearm_helper2",
            "skel:b_r_forearm_helper1",
            "skel:b_r_elbow_fixup",
            "skel:b_r_elbow_armor",
            "skel:b_r_shoulder_fixup",
            "skel:b_r_upperarm_fixup",
            "skel:b_r_shoulder_helper1",
            "skel:b_r_shoulder_helper2",
            "skel:b_r_shoulder_helper3",
            "skel:b_r_shoulder_helper4",
            "skel:b_r_upperarm_ctwist",
            "skel:b_torso",
            "skel:b_backpack",
            "skel:b_l_scap1",
            "skel:b_l_scap2",
            "skel:b_l_scap3",
            "skel:b_r_scap1",
            "skel:b_r_scap2",
            "skel:b_r_scap3",
            "skel:b_l_lowerback_armor",
            "skel:b_abarmor",
            "skel:b_backarmor",
            "skel:b_r_lowerback_armor",
            "skel:b_camera",
            "skel:b_neck0_ik",
            "skel:b_neck1_ik",
            "skel:b_head_ik",
            "skel:b_head_ik_eff",
            "skel:b_head_ctwist",
            "skel:b_spine2_twist",
            "skel:b_spine1_twist",
            "skel:b_l_thigh",
            "skel:b_l_calf",
            "skel:b_l_foot",
            "skel:b_l_toe",
            "skel:b_l_calf_jiggle",
            "skel:b_l_upperleg_jiggle",
            "skel:b_l_knee_fixup",
            "skel:b_l_thigh_helper",
            "skel:b_r_thigh",
            "skel:b_r_calf",
            "skel:b_r_foot",
            "skel:b_r_toe",
            "skel:b_r_calf_jiggle",
            "skel:b_r_upperleg_jiggle",
            "skel:b_r_knee_fixup",
            "skel:b_r_thigh_helper",
            "skel:b_r_thigh_ctwist",
            "skel:b_l_thigh_ctwist",
            "skel:b_l_glut_ctwist",
            "skel:b_r_glut_ctwist",
            "skel:b_spine1_ik",
            "skel:b_spine2_ik",
            "skel:b_spine3_ik",
            "skel:b_spine3_ik_eff",
            "skel:b_spine_ctwist"
                                  ]

        key = 1
        #self.mapBones[key] = "mat1"
        #print(self.bonesNames)
        #print(self.mapBones[key])